#!/usr/bin/env bash

export AIRFLOW_VAR_DR_STORAGE_TYPE=LOCAL_FS
echo "AIRFLOW_VAR_DR_STORAGE_TYPE=$AIRFLOW_VAR_DR_STORAGE_TYPE"

#export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="sqlite:////usr/local/airflow/airflow.db"
#echo "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW__DATABASE__SQL_ALCHEMY_CONN"
